AllCops:
  ParserEngine: parser_prism
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/ItWithoutArgumentsInBlock:
  Enabled: false
